resolvers += Resolver.sonatypeRepo("releases")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"       % "0.9.27")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"       % "2.4.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"        % "0.5.3")
addSbtPlugin("io.spray"         % "sbt-revolver"       % "0.9.1")
addSbtPlugin("com.codecommit"   % "sbt-github-actions" % "0.10.1")
